name: update website
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd Portfolio_website
            git pull            
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          args: "-tt"

